### PR TITLE
flake: add Nix shell for infrastructure work

### PR DESCRIPTION
**Pull request by jakubgs**

### CODE REVIEW

**Review by apentori — APPROVED** [review]

**Comment by yakimant** [comment]
```
error: Package ‘traceroute-2.1.5’ in /nix/store/fjs1x9gz2n1dvjqcyyl6qsw110qxc2zn-source/pkgs/tools/networking/traceroute/default.nix:26 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
```

**Comment by yakimant** [comment]
`bitwarden-cli-2024.4.1` build issue:
```
FileNotFoundError: [Errno 2] No such file or directory: 'xcrun'
```

**Review by siddarthkay — APPROVED** [review]
Lets make this a reality

**Comment by jakubgs** [comment]
There was a fix for Darwin build of Bitwarden CLI tool merged into master 2 days ago:

* https://github.com/NixOS/nixpkgs/pull/323588

We just need to wait for it to arrive in `nixos-unstable`.

**Comment by jakubgs** [comment]
It works on an M1 mac now:
```
jakubgs@macm1-01.ih-eu-mda1.ci.devel:~/infra-template % nix develop                  
infra-role-bootstrap-linux       ---       MISSING (Git: ........ | Req: *)
infra-role-wireguard             ---       MISSING (Git: ........ | Req: *)
infra-role-open-ports            ---       MISSING (Git: ........ | Req: *)
infra-role-swap-file             ---       MISSING (Git: ........ | Req: *)
infra-role-consul-service        ---       MISSING (Git: ........ | Req: *)
infra-role-systemd-timer         ---       MISSING (Git: ........ | Req: *)

WARNING: Your role versions appear to be incorrect!
macm1-01:infra-template jakubgs$ 
```

**Pull request merged**
